import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const noto = Noto_Sans_KR({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`centered h-dvh flex-col sm:gap-1 sm:p-4 ${noto.className} sm:flex-row`}
      >
        <div className="flex w-full max-w-[1440px]">
          <div className="min-w-[150px] border">ㅎㅇ</div>
          {children}
        </div>
      </body>
    </html>
  );
}
