import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import { Nav } from "./_assets/layouts/nav";
import { PageHeader } from "./_assets/layouts/page-header";

const inter = Inter({ subsets: ["latin"] });

const noto = Noto_Sans_KR({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`centered h-dvh ${noto.className}`}>
        <div className="flex m-4 w-full h-[95vh] max-w-[1440px] rounded-lg border shadow-xl">
          <Nav />
          <main className="flex w-full h-full flex-col justify-start">
            <PageHeader />
            <div className="p-4">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
